import type { OnChainEvent } from "./event-types";

// Dummy authority for demo events
const DEMO_AUTHORITY = "DeMo1111111111111111111111111111111111111111";

export interface DemoEvent extends OnChainEvent {
  isDemoEvent: true;
  city: string;
  date: string;
}

export const DEMO_EVENTS: DemoEvent[] = [
  // ═══════════════════════════════════════════════
  // CONFERENCE / MEETUP (type 0) — 12 events
  // ═══════════════════════════════════════════════
  { pda: "demo-001", authority: DEMO_AUTHORITY, eventId: 1001, name: "ETH Latam 2026 — Lima", description: "The largest Ethereum conference in Latin America. 3 days of talks, workshops, and networking with top builders.", ticketPrice: 1_500_000_000, maxTickets: 500, ticketsSold: 347, isActive: true, eventType: 0, isDemoEvent: true, city: "Lima", date: "2026-04-15" },
  { pda: "demo-002", authority: DEMO_AUTHORITY, eventId: 1002, name: "Solana Hacker House CDMX", description: "Week-long co-working and hacking event for Solana builders. Workshops, office hours with core devs, and demo day.", ticketPrice: 500_000_000, maxTickets: 120, ticketsSold: 89, isActive: true, eventType: 0, isDemoEvent: true, city: "Ciudad de Mexico", date: "2026-05-03" },
  { pda: "demo-003", authority: DEMO_AUTHORITY, eventId: 1003, name: "LABITCONF 2026 Buenos Aires", description: "Latin American Bitcoin & Blockchain Conference. The OG crypto conference of the region since 2013.", ticketPrice: 2_000_000_000, maxTickets: 800, ticketsSold: 612, isActive: true, eventType: 0, isDemoEvent: true, city: "Buenos Aires", date: "2026-11-12" },
  { pda: "demo-004", authority: DEMO_AUTHORITY, eventId: 1004, name: "Blockchain Summit Santiago", description: "Chile's premier blockchain conference. Enterprise adoption, DeFi, and regulation panels.", ticketPrice: 1_000_000_000, maxTickets: 300, ticketsSold: 156, isActive: true, eventType: 0, isDemoEvent: true, city: "Santiago", date: "2026-06-20" },
  { pda: "demo-005", authority: DEMO_AUTHORITY, eventId: 1005, name: "Web3 Builders Meetup Medellin", description: "Monthly meetup for Web3 developers in Medellin. Lightning talks, project demos, and pizza.", ticketPrice: 10_000_000, maxTickets: 60, ticketsSold: 42, isActive: true, eventType: 0, isDemoEvent: true, city: "Medellin", date: "2026-04-08" },
  { pda: "demo-006", authority: DEMO_AUTHORITY, eventId: 1006, name: "Solana Superteam Hackathon GDL", description: "48-hour hackathon by Solana Superteam Mexico. Build on Solana Actions, DePIN, or DeFi. $50K in prizes.", ticketPrice: 100_000_000, maxTickets: 200, ticketsSold: 178, isActive: true, eventType: 0, isDemoEvent: true, city: "Guadalajara", date: "2026-05-17" },
  { pda: "demo-007", authority: DEMO_AUTHORITY, eventId: 1007, name: "Devcon Satellite — Bogota", description: "Official Devcon satellite event in Colombia. Core protocol talks and community meetups.", ticketPrice: 800_000_000, maxTickets: 400, ticketsSold: 298, isActive: true, eventType: 0, isDemoEvent: true, city: "Bogota", date: "2026-09-05" },
  { pda: "demo-008", authority: DEMO_AUTHORITY, eventId: 1008, name: "Crypto Monterrey Tech Week", description: "Week of events around crypto, AI, and fintech in Monterrey. Hosted by local tech ecosystem.", ticketPrice: 600_000_000, maxTickets: 250, ticketsSold: 91, isActive: true, eventType: 0, isDemoEvent: true, city: "Monterrey", date: "2026-07-14" },
  { pda: "demo-009", authority: DEMO_AUTHORITY, eventId: 1009, name: "Ethereum Peru Meetup #12", description: "Monthly Ethereum community meetup in Lima. Solidity workshops for beginners and intermediate devs.", ticketPrice: 20_000_000, maxTickets: 80, ticketsSold: 53, isActive: true, eventType: 0, isDemoEvent: true, city: "Lima", date: "2026-04-22" },
  { pda: "demo-010", authority: DEMO_AUTHORITY, eventId: 1010, name: "Starknet LATAM Day — CDMX", description: "One-day deep dive into Starknet and Cairo. ZK proofs, account abstraction, and scaling.", ticketPrice: 300_000_000, maxTickets: 150, ticketsSold: 67, isActive: true, eventType: 0, isDemoEvent: true, city: "Ciudad de Mexico", date: "2026-06-03" },
  { pda: "demo-011", authority: DEMO_AUTHORITY, eventId: 1011, name: "Polkadot Decoded Cordoba", description: "Polkadot community event in Argentina. Parachain workshops, governance talks, and networking.", ticketPrice: 400_000_000, maxTickets: 180, ticketsSold: 72, isActive: true, eventType: 0, isDemoEvent: true, city: "Cordoba", date: "2026-08-19" },
  { pda: "demo-012", authority: DEMO_AUTHORITY, eventId: 1012, name: "DeFi Summit Cartagena", description: "Two-day conference on DeFi protocols, yield strategies, and on-chain risk management.", ticketPrice: 1_200_000_000, maxTickets: 350, ticketsSold: 201, isActive: true, eventType: 0, isDemoEvent: true, city: "Cartagena", date: "2026-10-08" },

  // ═══════════════════════════════════════════════
  // RESEARCH / DESCI (type 1) — 8 events
  // ═══════════════════════════════════════════════
  { pda: "demo-013", authority: DEMO_AUTHORITY, eventId: 1013, name: "DeSci Lima — Blockchain Research Grant", description: "Fund open science research on Solana. Proposals from PUCP, San Marcos, and UNI researchers.", ticketPrice: 500_000_000, maxTickets: 100, ticketsSold: 78, isActive: true, eventType: 1, isDemoEvent: true, city: "Lima", date: "2026-05-10" },
  { pda: "demo-014", authority: DEMO_AUTHORITY, eventId: 1014, name: "Beca Blockchain UNAM 2026", description: "Scholarship fund for UNAM students researching blockchain scalability and privacy.", ticketPrice: 200_000_000, maxTickets: 50, ticketsSold: 34, isActive: true, eventType: 1, isDemoEvent: true, city: "Ciudad de Mexico", date: "2026-04-30" },
  { pda: "demo-015", authority: DEMO_AUTHORITY, eventId: 1015, name: "Workshop: ZK Proofs for Academia", description: "Academic workshop on zero-knowledge proofs. Hosted by Universidad de Chile CS department.", ticketPrice: 100_000_000, maxTickets: 40, ticketsSold: 28, isActive: true, eventType: 1, isDemoEvent: true, city: "Santiago", date: "2026-06-15" },
  { pda: "demo-016", authority: DEMO_AUTHORITY, eventId: 1016, name: "ITESM Blockchain Research Symposium", description: "Annual research symposium at Tec de Monterrey. Papers on consensus, tokenomics, and regulation.", ticketPrice: 150_000_000, maxTickets: 120, ticketsSold: 45, isActive: true, eventType: 1, isDemoEvent: true, city: "Monterrey", date: "2026-09-22" },
  { pda: "demo-017", authority: DEMO_AUTHORITY, eventId: 1017, name: "DeSci Andes — Research Funding Pool", description: "Crowdfunded research grants for Andean universities. Topics: supply chain, identity, and agriculture on-chain.", ticketPrice: 300_000_000, maxTickets: 80, ticketsSold: 61, isActive: true, eventType: 1, isDemoEvent: true, city: "Cusco", date: "2026-07-08" },
  { pda: "demo-018", authority: DEMO_AUTHORITY, eventId: 1018, name: "UBA Crypto Economics Seminar", description: "University of Buenos Aires seminar on crypto economics, MEV, and mechanism design.", ticketPrice: 50_000_000, maxTickets: 60, ticketsSold: 44, isActive: true, eventType: 1, isDemoEvent: true, city: "Buenos Aires", date: "2026-05-28" },
  { pda: "demo-019", authority: DEMO_AUTHORITY, eventId: 1019, name: "Biotech x Blockchain Bogota", description: "Exploring blockchain applications in biotech: clinical trials on-chain, IP-NFTs, and data sovereignty.", ticketPrice: 400_000_000, maxTickets: 90, ticketsSold: 37, isActive: true, eventType: 1, isDemoEvent: true, city: "Bogota", date: "2026-08-05" },
  { pda: "demo-020", authority: DEMO_AUTHORITY, eventId: 1020, name: "Grant Pool: AI x Web3 Research", description: "Funding pool for research at the intersection of AI agents and blockchain. Open to all LATAM universities.", ticketPrice: 1_000_000_000, maxTickets: 200, ticketsSold: 143, isActive: true, eventType: 1, isDemoEvent: true, city: "Arequipa", date: "2026-10-15" },

  // ═══════════════════════════════════════════════
  // ART & MUSIC (type 2) — 8 events
  // ═══════════════════════════════════════════════
  { pda: "demo-021", authority: DEMO_AUTHORITY, eventId: 1021, name: "NFT Art Week Lima", description: "Week-long exhibition of generative art, on-chain photography, and digital sculptures by LATAM artists.", ticketPrice: 200_000_000, maxTickets: 300, ticketsSold: 189, isActive: true, eventType: 2, isDemoEvent: true, city: "Lima", date: "2026-04-18" },
  { pda: "demo-022", authority: DEMO_AUTHORITY, eventId: 1022, name: "Sonidos On-Chain — Album Release", description: "Live album release party by DJ Crypto_Beat. Music minted as NFTs on Solana. Rooftop venue in Medellin.", ticketPrice: 150_000_000, maxTickets: 200, ticketsSold: 167, isActive: true, eventType: 2, isDemoEvent: true, city: "Medellin", date: "2026-05-24" },
  { pda: "demo-023", authority: DEMO_AUTHORITY, eventId: 1023, name: "Muralismo Digital — Valparaiso", description: "Digital muralism meets blockchain. Artists create on-chain murals projected on Valparaiso's hills.", ticketPrice: 80_000_000, maxTickets: 150, ticketsSold: 98, isActive: true, eventType: 2, isDemoEvent: true, city: "Valparaiso", date: "2026-06-28" },
  { pda: "demo-024", authority: DEMO_AUTHORITY, eventId: 1024, name: "Crypto Beats Festival CDMX", description: "Electronic music festival powered by crypto. All tickets as NFTs. Lineup TBA. 3 stages, 1 night.", ticketPrice: 500_000_000, maxTickets: 1000, ticketsSold: 743, isActive: true, eventType: 2, isDemoEvent: true, city: "Ciudad de Mexico", date: "2026-07-19" },
  { pda: "demo-025", authority: DEMO_AUTHORITY, eventId: 1025, name: "Arte Generativo Buenos Aires", description: "Exhibition of generative art created with on-chain randomness. Featured artists from AR, CL, and PE.", ticketPrice: 100_000_000, maxTickets: 250, ticketsSold: 112, isActive: true, eventType: 2, isDemoEvent: true, city: "Buenos Aires", date: "2026-08-10" },
  { pda: "demo-026", authority: DEMO_AUTHORITY, eventId: 1026, name: "Fotografía On-Chain Cartagena", description: "Photography exhibition where each piece is a compressed NFT on Solana. Caribbean landscapes and portraits.", ticketPrice: 60_000_000, maxTickets: 100, ticketsSold: 51, isActive: true, eventType: 2, isDemoEvent: true, city: "Cartagena", date: "2026-09-14" },
  { pda: "demo-027", authority: DEMO_AUTHORITY, eventId: 1027, name: "Indie Music x Solana — GDL", description: "Showcase of indie bands releasing music on-chain. Fan tokens, royalty splits, and live performances.", ticketPrice: 120_000_000, maxTickets: 180, ticketsSold: 134, isActive: true, eventType: 2, isDemoEvent: true, city: "Guadalajara", date: "2026-06-07" },
  { pda: "demo-028", authority: DEMO_AUTHORITY, eventId: 1028, name: "Poesia NFT — Cusco", description: "Poetry meets blockchain. Poets mint their work as NFTs. Live readings in Cusco's historic center.", ticketPrice: 30_000_000, maxTickets: 70, ticketsSold: 48, isActive: true, eventType: 2, isDemoEvent: true, city: "Cusco", date: "2026-05-15" },

  // ═══════════════════════════════════════════════
  // COMMUNITY / DAO (type 3) — 8 events
  // ═══════════════════════════════════════════════
  { pda: "demo-029", authority: DEMO_AUTHORITY, eventId: 1029, name: "Solana Superteam Peru — Town Hall", description: "Quarterly town hall for Solana Superteam Peru. Budget review, project updates, and new member onboarding.", ticketPrice: 10_000_000, maxTickets: 80, ticketsSold: 62, isActive: true, eventType: 3, isDemoEvent: true, city: "Lima", date: "2026-04-25" },
  { pda: "demo-030", authority: DEMO_AUTHORITY, eventId: 1030, name: "CryptoMujeres DAO — Meetup CDMX", description: "Community meetup for women in crypto. Workshops on DeFi, career paths, and building in Web3.", ticketPrice: 20_000_000, maxTickets: 100, ticketsSold: 73, isActive: true, eventType: 3, isDemoEvent: true, city: "Ciudad de Mexico", date: "2026-05-08" },
  { pda: "demo-031", authority: DEMO_AUTHORITY, eventId: 1031, name: "ReFi Colombia — Climate DAO Assembly", description: "Regenerative finance DAO meeting. Proposals for reforestation credits, carbon offsets on Solana.", ticketPrice: 50_000_000, maxTickets: 60, ticketsSold: 41, isActive: true, eventType: 3, isDemoEvent: true, city: "Bogota", date: "2026-06-12" },
  { pda: "demo-032", authority: DEMO_AUTHORITY, eventId: 1032, name: "DAO Governance Workshop Santiago", description: "Hands-on workshop on DAO governance: Realms, SPL Governance, and quadratic voting.", ticketPrice: 100_000_000, maxTickets: 50, ticketsSold: 35, isActive: true, eventType: 3, isDemoEvent: true, city: "Santiago", date: "2026-07-03" },
  { pda: "demo-033", authority: DEMO_AUTHORITY, eventId: 1033, name: "Builders DAO Argentina — Sprint", description: "Week-long building sprint by Argentina's largest builder DAO. Teams compete for grant funding.", ticketPrice: 200_000_000, maxTickets: 40, ticketsSold: 38, isActive: true, eventType: 3, isDemoEvent: true, city: "Cordoba", date: "2026-08-25" },
  { pda: "demo-034", authority: DEMO_AUTHORITY, eventId: 1034, name: "Public Goods Funding Round Lima", description: "Gitcoin-style quadratic funding round for Peruvian public goods projects. All on Solana.", ticketPrice: 500_000_000, maxTickets: 150, ticketsSold: 118, isActive: true, eventType: 3, isDemoEvent: true, city: "Lima", date: "2026-09-18" },
  { pda: "demo-035", authority: DEMO_AUTHORITY, eventId: 1035, name: "NFT Creators Guild — Medellin Chapter", description: "Monthly meetup of the NFT Creators Guild. Portfolio reviews, collaboration matchmaking, and pizza.", ticketPrice: 15_000_000, maxTickets: 45, ticketsSold: 31, isActive: true, eventType: 3, isDemoEvent: true, city: "Medellin", date: "2026-04-12" },
  { pda: "demo-036", authority: DEMO_AUTHORITY, eventId: 1036, name: "Superteam Mexico — Town Hall MTY", description: "Quarterly planning session for Superteam Mexico Monterrey chapter. Grants, events, and roadmap.", ticketPrice: 10_000_000, maxTickets: 55, ticketsSold: 40, isActive: true, eventType: 3, isDemoEvent: true, city: "Monterrey", date: "2026-06-25" },

  // ═══════════════════════════════════════════════
  // OTHER (type 4) — 4 events
  // ═══════════════════════════════════════════════
  { pda: "demo-037", authority: DEMO_AUTHORITY, eventId: 1037, name: "Crypto Nomad Coworking — Arequipa", description: "Pop-up coworking space for crypto nomads. Fast wifi, coffee, and builder vibes in the white city.", ticketPrice: 50_000_000, maxTickets: 30, ticketsSold: 22, isActive: true, eventType: 4, isDemoEvent: true, city: "Arequipa", date: "2026-05-20" },
  { pda: "demo-038", authority: DEMO_AUTHORITY, eventId: 1038, name: "Solana Pay Merchants Workshop", description: "Teaching local merchants in Cartagena how to accept Solana Pay. Practical setup and integration.", ticketPrice: 10_000_000, maxTickets: 40, ticketsSold: 27, isActive: true, eventType: 4, isDemoEvent: true, city: "Cartagena", date: "2026-07-30" },
  { pda: "demo-039", authority: DEMO_AUTHORITY, eventId: 1039, name: "Web3 Gaming Tournament GDL", description: "Gaming tournament featuring on-chain games built on Solana. Star Atlas, Aurory, and indie titles.", ticketPrice: 80_000_000, maxTickets: 200, ticketsSold: 156, isActive: true, eventType: 4, isDemoEvent: true, city: "Guadalajara", date: "2026-08-15" },
  { pda: "demo-040", authority: DEMO_AUTHORITY, eventId: 1040, name: "Bitcoin Pizza Day — Buenos Aires", description: "Annual celebration of Bitcoin Pizza Day. Free pizza, lightning network demos, and trivia night.", ticketPrice: 10_000_000, maxTickets: 150, ticketsSold: 142, isActive: true, eventType: 4, isDemoEvent: true, city: "Buenos Aires", date: "2026-05-22" },
];
